### ISSUE TITLE
LDAP Rancher template 1.0 bombs out after succesfull connect

### ISSUE THREAD

**Issue by twobombs** [mdnsfr/docker-rancher-openvpn#1]
![screenshot 2016-05-10 12 18 17](https://cloud.githubusercontent.com/assets/12692227/15143330/61979628-16a9-11e6-8826-0bb5edc62872.png)
- update: also found this with the basic template

The LDAP OpenVPN template 1.0 on Rancher 1.x behaves erratic in a vCloud/ESXi enviroment.

Running Docker 1.1.0 on Ubuntu 14.04LTS

After initial connect succesfull or unsuccesfull authentication the port 1194/tcp bombs out and doesn't come back. The service just stops, clients disconnect ( retry in 5 secs )

It is the last piece of a setup we're doing here; we need it for the managed network hosts network.

Is there any1 out there with some pointers or a blogpost of sorts that show OpenVPN LDAP template 1.0 actually works on rancher 1.01 ?

**Comment by AlexisDucastel** [comment]
Hi @twobombs, Did you try to setup this VPN through the Rancher catalog entry ? It's very easy to setup and really drives you to a correct configuration.

**Comment by twobombs** [comment]
Hi Alexis,

An upgrade of Rancher 1.0 to 1.1.0 helped fix this issue. 
It now works out of the box. 

tnx

**Comment by AlexisDucastel** [comment]
Okay that's great ! Have fun with  it ;)

**Comment by twobombs** [comment]
Found a similar problem resurface with Rancher 1.14 & docker 1.12.x 

![screenshot 2016-11-10 16 06 11](https://cloud.githubusercontent.com/assets/12692227/20181835/035aa6e8-a760-11e6-9336-963cdd5edd88.png)
<img width="974" alt="screenshot 2016-11-10 16 06 03" src="https://cloud.githubusercontent.com/assets/12692227/20181834/035a11ce-a760-11e6-93f2-8f2ebb94c618.png">

problem occurs when the container is launched within rancher, the same issue also happens when I use the template. Launching as a container from the commandline the problem does not occur.

This is killing scaling, am i really the only one on the planet with this issue ?

**Comment by twobombs** [comment]
can be closed: auth.env had wrong values
