### ISSUE TITLE
Some env vars already "baked into" entrypoint script

### ISSUE THREAD

**Issue by Dhar** [mdnsfr/docker-rancher-openvpn#12]
I was having trouble setting a custom route via environment variables.  Looking in entry.sh in the git repo for the section that writes out `server.conf` and `client.conf`, it seemed like assigning values to the `ROUTE_NETWORK` and `ROUTE_NETMASK` env vars would accomplish this:

```
[...]
server $VPNPOOL_NETWORK $VPNPOOL_NETMASK
push "dhcp-option DNS $PUSHDNS"
push "dhcp-option SEARCH $PUSHSEARCH"
push "route $ROUTE_NETWORK $ROUTE_NETMASK"
$RANCHER_METADATA_API
keepalive 10 120
[...]
```

It wasn't working.  Opening a terminal to the container itself revealed the actual contents of `entry.sh` are:

```
[...]
server $VPNPOOL_NETWORK $VPNPOOL_NETMASK
push "dhcp-option DNS 169.254.169.250"
push "dhcp-option SEARCH rancher.internal"
push "route 10.42.0.0 255.255.0.0"
push "route 169.254.169.250 255.255.255.255"
keepalive 10 120
[...]
```

Is it possible that mdns/rancher-openvpn-1.1 was built inside an environment where some env vars were already set, and so accidentally "baked in"?

-g.

**Comment by enavarro222** [comment]
I got the same issue, but this has been fix in 1.2 version ! 

One can close this issue.
