### ISSUE TITLE
Multiline OPENVPN_EXTRACONF

### ISSUE THREAD

**Issue by JStumpp** [mdnsfr/docker-rancher-openvpn#4]
The OPENVPN_EXTRACONF should accept multiple lines (e.g. separated with \n)

and the default configuration parameters should be removed from bin/entry.sh to be usable in general:
- push "dhcp-option DNS 169.254.169.250"
- push "dhcp-option SEARCH rancher.internal"
- push "route 10.42.0.0 255.255.0.0"
- push "route 169.254.169.250 255.255.255.255"

Thanks for the nice container!

**Comment by AlexisDucastel** [comment]
This makes sense ! I'll add something in this way for multiline extraconfig in next days.

> default configuration parameters should be removed from bin/entry.sh to be usable in general

Just to be sure, you suggest to introduce new environment variables to be able to customize these default parameters ?

Thanks for your help.

**Comment by JStumpp** [comment]
Yes, environment variables for the stuff that is always required:
push "dhcp-option DNS $DNS"
push "dhcp-option SEARCH $SEARCH"
push "route $ROUTE_NETWORK $ROUTE_NETMASK"

But the second route you defined I would move to the OPENVPN_EXTRACONF:
push "route 169.254.169.250 255.255.255.255"

Than it can be used as standalone without rancher as well.

Thanks!

**Comment by AlexisDucastel** [comment]
Done !

https://github.com/mdnsfr/docker-rancher-openvpn/commits/master
new docker image available : 1.2
https://hub.docker.com/r/mdns/rancher-openvpn/tags/

**Comment by JStumpp** [comment]
Wonderful, thanks!
